

find_package(Qt6 QUIET REQUIRED COMPONENTS Widgets Gui Core Network)
set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTORCC ON)
set(CMAKE_AUTOUIC ON)

option(VC_WITH_CUDA_SPARSE "use cudss" ON)
if (VC_WITH_CUDA_SPARSE)
    add_definitions(-DVC_USE_CUDA_SPARSE=1)
endif()

find_package(Ceres REQUIRED)
include(BuildZ5)
find_package(Eigen3 3.3 REQUIRED)
find_package(OpenCV  QUIET REQUIRED)
set(XTENSOR_USE_XSIMD 1)
set(XTENSOR_USE_OPENMP 1)
find_package(xtensor REQUIRED)
find_package(OpenMP REQUIRED)
find_package(spdlog 1.4.2 CONFIG REQUIRED)
find_package(nlohmann_json 3.9.1 REQUIRED)
find_package(CURL REQUIRED)
find_package(Boost 1.58 REQUIRED COMPONENTS system program_options)
include(BuildIndicators)
